fix: correct describe with 2019년 to 2020년
toss/slash pull request #267
Opened 2023-06-16 08:27 UTC by minsoo-web

## Overview

Correct unit test describe with `2019` to `2020`

## PR Checklist

- [x] I read and included theses actions below

1. I have read the [Contributing Guide](https://github.com/toss/slash/blob/main/.github/CONTRIBUTING.md)
2. I have written documents and tests, if needed.

2023-06-17 01:04 UTC, ChanhyukPark-Tech requested changes
Why don't you change the test description to English? Slash seems to be ultimately aiming to provide all the codebases in English

2023-06-18 08:30 UTC, minsoo-web commented
Thank you, @ChanhyukPark-Tech 🙇‍♂️

> Why don't you change the test description to English? 

As you mentioned `seems`, I think there's nothing decided yet with locale description for test code.

I think this should be added to the contribution guide rather than what my PR should do. If the maintainer sets up a convention to write the test code in English, I will write a PR to correct it.

2023-06-22 17:00 UTC, ChanhyukPark-Tech commented
you can check future plan in this [comment](https://github.com/toss/slash/pull/36#issuecomment-1275899085)

2023-06-23 12:37 UTC, minsoo-web commented
> you can check future plan in this https://github.com/toss/slash/pull/36#issuecomment-1275899085

Thank you for guide.
I will change this kr to en

2023-06-30 16:13 UTC, ChanhyukPark-Tech commented on packages/common/date/src/date.spec.ts
> +    it("When don`t wants show '시간' unit.", () => {
`slash` use `it` keyword better than `test` keyword for method

`it` and `test` are functionally the same but semantically different.
```
it("should have a button", () => { ... }); // 1
test("should have a button", () => {}); // 2
```
You can read the code above as english sentence. Then which is the more easily readable? I think 1 is the winner.
```suggestion
    it("should not show '시간' unit", () => {
```

semantically in english

1. it should not show '시간' unit
2. it When don`t wants show '시간' unit.

I think 1 is more readibility🥳

ref: https://github.com/toss/slash/pull/37#discussion_r994630666

2023-06-30 17:31 UTC, minsoo-web commented on packages/common/date/src/date.spec.ts
> +    it("When don`t wants show '시간' unit.", () => {
Holy Cool man... i will fix `it`

2023-07-01 00:34 UTC, ChanhyukPark-Tech approved these changes
Cool!

2023-07-03 05:52 UTC, raon0211 approved these changes
Wow! This is great.

2023-07-03 05:53 UTC, merged